CREATE TABLE PUBLIC.PUBLIC.AUTHORITIES (
	ID BIGINT NOT NULL IDENTITY,
	NAME VARCHAR(128) NOT NULL,
	CONSTRAINT AUTHORITIES_PK PRIMARY KEY (ID)
);
--;;
CREATE INDEX AUTHORITIES_NAME_IDX ON PUBLIC.PUBLIC.AUTHORITIES (NAME);
